name: junitreport
version: 1.3.2-dev
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML

homepage: https://github.com/TOPdesk/dart-junitreport
documentation:

dependencies:
  args: ^1.6.0
  intl: ^0.16.1
  testreport:
    git:
      url: git@github.com:operando/dart-testreport.git
      ref: "7f4460f"
  xml: ^4.3.0

dev_dependencies:
  pedantic: ^1.9.0
  test: any

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  tojunit: